#!/bin/sh
#
# $Id: safe_xvb_perl_worker,v 1.4 2011-08-11 05:16:20 gosha Exp $
#
# vim:textwidth=80:tabstop=4:shiftwidth=4:smartindent:autoindent

#NOTIFY=ben@alkaloid.net	# Who to notify about crashes
#EXEC=/path/to/somescript	# Run this command if Asterisk crashes
MACHINE=`hostname`			# To specify which machine has crashed when getting the mail
SLEEPSECS=4
CONFIG=$1

# Check if is already running.
PROC=`ps ax | grep '[V]irtualPBX-perl-worker'`
if [ "x$PROC" != "x" ]; then
	echo "VirtualPBX perl worker is already running." 1>&2
	exit 1
fi

#
# Don't die if stdout/stderr can't be written to
#
trap '' PIPE

run_xvb()
{
	while :; do 
		cd /tmp
		sudo -u asterisk /opt/VirtualPBX/agi-bin/VirtualPBX.agi perl-worker $CONFIG
		EXITSTATUS=$?
		echo "ended with exit status $EXITSTATUS" 1>&2
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "shutdown normally." 1>&2
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			EXITSIGNAL=EXITSTATUS-128
			echo "XVB perl worker exited on signal $EXITSIGNAL."  1>&2
			if [ "$NOTIFY" != "" ]; then
				echo "XVB perl worker on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "XVB perl worker Died" $NOTIFY
			fi
			if [ "$EXEC" != "" ]; then
				$EXEC
			fi
		else
			echo "XVB perl worker exited on signal $EXITSIGNAL." 1>&2
		fi
		echo "Automatically restarting XVB perl worker." 1>&2
		date  1>&2
		sleep $SLEEPSECS
	done
}

run_xvb &
