#!/bin/bash
#
# $Id: safe_xvb_perl_worker,v 1.5 2012-02-02 11:40:00 gosha Exp $
#
# vim:textwidth=80:tabstop=4:shiftwidth=4:smartindent:autoindent

RC_CONFIG=${1-"/opt/VirtualPBX/etc/xvb-rc.cfg"}
. ${RC_CONFIG}

# Check if is already running.
PROC=`ps ax | grep '[V]irtualPBX-perl-worker'`
if [ "x$PROC" != "x" ]; then
	echo "VirtualPBX perl worker is already running." 
	exit 1
fi

#
# Don't die if stdout/stderr can't be written to
#
trap '' PIPE

run_xvb()
{
	while :; do 
		cd /tmp
		sudo -u asterisk /opt/VirtualPBX/agi-bin/VirtualPBX.agi perl-worker $XVB_CONFIG
		EXITSTATUS=$?
		echo "ended with exit status $EXITSTATUS" 
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "shutdown normally." 
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			EXITSIGNAL=EXITSTATUS-128
			echo "XVB perl worker exited on signal $EXITSIGNAL."  
			if [ "$NOTIFY" != "" ]; then
				echo "XVB perl worker on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "XVB perl worker Died" $NOTIFY
			fi
			if [ "$PERL_WORKER_EXEC" != "" ]; then
				$PERL_WORKER_EXEC
			fi
		else
			echo "XVB perl worker exited on signal $EXITSIGNAL." 
		fi
		echo "Automatically restarting XVB perl worker." 
		date  
		sleep $SLEEPSECS
	done
}

run_xvb 2>>/var/log/VirtualPBX/XVB.stderr 1>&2 &
