#!/bin/sh
#
# $Id: safe_xvb_agi,v 1.1 2009-11-14 14:50:02 gosha Exp $
#
# vim:textwidth=80:tabstop=4:shiftwidth=4:smartindent:autoindent

#NOTIFY=ben@alkaloid.net	# Who to notify about crashes
#EXEC=/path/to/somescript	# Run this command if Asterisk crashes
MACHINE=`hostname`			# To specify which machine has crashed when getting the mail
SLEEPSECS=4
CONFIG=$1
CHILDS=$2

# Check if is already running.
PROC=`ps ax | grep '[fF]agi.pl'`
if [ "x$PROC" != "x" ]; then
	echo "Fagi is already running."
	exit 1
fi

#
# Don't die if stdout/stderr can't be written to
#
trap '' PIPE

run_xvb()
{
	while :; do 
		cd /tmp
		/opt/VirtualPBX/contrib/utils/Fagi.pl $CONFIG $CHILDS
		EXITSTATUS=$?
		echo "ended with exit status $EXITSTATUS"
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "shutdown normally."
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			EXITSIGNAL=EXITSTATUS-128
			echo "XVB exited on signal $EXITSIGNAL."
			if [ "$NOTIFY" != "" ]; then
				echo "XVB AGI server on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "XVB AGI server Died" $NOTIFY
			fi
			if [ "$EXEC" != "" ]; then
				$EXEC
			fi
		else
			echo "XVB exited on signal $EXITSIGNAL."
		fi
		echo "Automatically restarting XVB AGI server."
		sleep $SLEEPSECS
	done
}

run_xvb &
